; validation/functional_test_6801.asm -- a self-checking MC6800/MC6801/MC6803-only extension test.
;
; Copyright (c) 2026 the m6800-python contributors.
;
; Permission is hereby granted, free of charge, to any person obtaining a
; copy of this software and associated documentation files (the "Software"),
; to deal in the Software without restriction, including without limitation
; the rights to use, copy, modify, merge, publish, distribute, sublicense,
; and/or sell copies of the Software, and to permit persons to whom the
; Software is furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in
; all copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
; FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
; DEALINGS IN THE SOFTWARE.
;
; Generated by scripts/gen_functional_test.py -- see that file's docstring
; for how each expected value was derived, and for this program's scope (one
; representative case per documented mnemonic; WAI is the one mnemonic no
; freestanding self-test can exercise, for want of an interrupt source).
;
; Every check follows the same shape: set up registers and flags, run the
; opcode under test, then verify -- flags first (any comparison instruction
; would itself overwrite them), then any result value. A wrong answer lands
; on its own FAILnnn trap, a tight BRA to itself, so the program counter
; alone identifies which check failed; a correct run reaches SUCCESS with A
; holding $AA.
;
; Change ORIGIN and SCRATCH below to match your board's RAM map, reassemble
; with scripts/asm6800.py, and burn or load the result. See docs/README.md
; and the "Hardware owners" section of validation.md for how to report back.

ORIGIN	EQU	$1000
SCRATCH	EQU	$40
SAVE	EQU	$42

	ORG	ORIGIN
START:
	LDS #$01FF
; CPX (6801: true 16-bit) X=$0001 #$8000
	LDAA #$3F
	TAP
	LDX #$0001
	CPX #$8000
	TPA
	ANDA #$3F
	CMPA #$3B
	BEQ OK001
FAIL001:	BRA FAIL001
OK001:
	CPX #$0001
	BEQ OK002
FAIL002:	BRA FAIL002
OK002:
; MUL $19 * $EF = $1757
	LDAA #$3F
	TAP
	LDAA #$19
	LDAB #$EF
	MUL
	PSHA
	TPA
	ANDA #$3F
	CMPA #$38
	BEQ OK003
FAIL003:	BRA FAIL003
OK003:
	PULA
	CMPA #$17
	BEQ OK004
FAIL004:	BRA FAIL004
OK004:
	CMPB #$57
	BEQ OK005
FAIL005:	BRA FAIL005
OK005:
; ABX X=$12F0 + B=$FF = $13EF
	LDAA #$3F
	TAP
	LDX #$12F0
	LDAB #$FF
	ABX
	TPA
	ANDA #$3F
	CMPA #$39
	BEQ OK006
FAIL006:	BRA FAIL006
OK006:
	CPX #$13EF
	BEQ OK007
FAIL007:	BRA FAIL007
OK007:
; ADDD D=$7FFF #$0001 = $8000
	LDAA #$3F
	TAP
	LDAA #$7F
	LDAB #$FF
	ADDD #$0001
	PSHA
	TPA
	ANDA #$3F
	CMPA #$3A
	BEQ OK008
FAIL008:	BRA FAIL008
OK008:
	PULA
	CMPA #$80
	BEQ OK009
FAIL009:	BRA FAIL009
OK009:
	CMPB #$00
	BEQ OK010
FAIL010:	BRA FAIL010
OK010:
; SUBD D=$8000 #$0001 = $7FFF
	LDAA #$3F
	TAP
	LDAA #$80
	LDAB #$00
	SUBD #$0001
	PSHA
	TPA
	ANDA #$3F
	CMPA #$32
	BEQ OK011
FAIL011:	BRA FAIL011
OK011:
	PULA
	CMPA #$7F
	BEQ OK012
FAIL012:	BRA FAIL012
OK012:
	CMPB #$FF
	BEQ OK013
FAIL013:	BRA FAIL013
OK013:
; ASLD D=$C001 = $8002
	LDAA #$31
	TAP
	LDAA #$C0
	LDAB #$01
	ASLD
	PSHA
	TPA
	ANDA #$3F
	CMPA #$39
	BEQ OK014
FAIL014:	BRA FAIL014
OK014:
	PULA
	CMPA #$80
	BEQ OK015
FAIL015:	BRA FAIL015
OK015:
	CMPB #$02
	BEQ OK016
FAIL016:	BRA FAIL016
OK016:
; LSRD D=$8001 = $4000
	LDAA #$31
	TAP
	LDAA #$80
	LDAB #$01
	LSRD
	PSHA
	TPA
	ANDA #$3F
	CMPA #$33
	BEQ OK017
FAIL017:	BRA FAIL017
OK017:
	PULA
	CMPA #$40
	BEQ OK018
FAIL018:	BRA FAIL018
OK018:
	CMPB #$00
	BEQ OK019
FAIL019:	BRA FAIL019
OK019:
; LDD #$8001
	LDAA #$3F
	TAP
	LDD #$8001
	PSHA
	TPA
	ANDA #$3F
	CMPA #$39
	BEQ OK020
FAIL020:	BRA FAIL020
OK020:
	PULA
	CMPA #$80
	BEQ OK021
FAIL021:	BRA FAIL021
OK021:
	CMPB #$01
	BEQ OK022
FAIL022:	BRA FAIL022
OK022:
; STD $8001 -> SCRATCH
	LDAA #$3F
	TAP
	LDD #$8001
	STD <SCRATCH
	TPA
	ANDA #$3F
	CMPA #$39
	BEQ OK023
FAIL023:	BRA FAIL023
OK023:
	LDX <SCRATCH
	CPX #$8001
	BEQ OK024
FAIL024:	BRA FAIL024
OK024:
; BRN never branches
	LDAA #$3F
	TAP
	BRN OK025
FAIL025:
	BRA BRN_DONE
OK025:
	BRA OK025
BRN_DONE:
; PSHX / PULX round-trip
; PSHX / PULX round-trip
	LDAA #$3F
	TAP
	LDX #$1234
	PSHX
	LDX #$0000
	PULX
	CPX #$1234
	BEQ OK026
FAIL026:	BRA FAIL026
OK026:
SUCCESS:
	LDAA	#$AA
DONE:	BRA	DONE

; A board's own peripherals could raise IRQ or NMI during this test (a free-
; running timer, say); route anything this program did not arrange itself to
; a trap with its own identifiable address rather than into whatever happens
; to sit at the vector target.
UNEXPECTED_INTERRUPT:
	BRA	UNEXPECTED_INTERRUPT

	ORG	$FFF8
	FDB	UNEXPECTED_INTERRUPT	; IRQ ($FFF8/$FFF9)
	FDB	UNEXPECTED_INTERRUPT		; SWI  ($FFFA/$FFFB)
	FDB	UNEXPECTED_INTERRUPT	; NMI  ($FFFC/$FFFD)
	FDB	START			; RESET ($FFFE/$FFFF)
	END
